skeleton/config/routes.rb
Rails.application.routes.draw do

  resources :skills
  resources :skill_categories
  resources :projects

  resources :jobs
  get 'find/my/job' => 'jobs#find'

  resources :companies

  root 'home#index'

  devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations" } #, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    post 'pay', to: 'users/registrations#pay'
  end

  resources :charges

  get 'cart' => 'home#cart'
  get 'contact' => 'home#contact'
  get 'about' => 'home#about'
  get 'blog' => 'home#blog'
  get 'blog/post' => 'home#blog_post'
  get 'invoice' => 'home#invoice'
  get 'premium' => 'home#premium'

  get 'account' => 'account#index', as: :user
  patch 'account/update' => 'account#update'

end

skeleton/app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :skill_category
  belongs_to :user
end

skeleton/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:skill_category_id, :name, :date, :score, :level, :rank)
    end
end

skeleton/app/helpers/skills_helper.rb
module SkillsHelper
end

skeleton/app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill_category_id %><br>
    <%= f.text_field :skill_category_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skeleton/app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

skeleton/app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skills</h1>

<table>
  <thead>
    <tr>
      <th>Skill category</th>
      <th>Name</th>
      <th>Date</th>
      <th>Score</th>
      <th>Level</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.skill_category %></td>
        <td><%= skill.name %></td>
        <td><%= skill.date %></td>
        <td><%= skill.score %></td>
        <td><%= skill.level %></td>
        <td><%= skill.rank %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

skeleton/app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

skeleton/app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skill category:</strong>
  <%= @skill.skill_category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @skill.date %>
</p>

<p>
  <strong>Score:</strong>
  <%= @skill.score %>
</p>

<p>
  <strong>Level:</strong>
  <%= @skill.level %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @skill.rank %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>