skeleton/config/routes.rb
Rails.application.routes.draw do

  resources :skills
  resources :skill_categories
  resources :projects

  resources :jobs
  get 'find/my/job' => 'jobs#find'

  resources :companies

  root 'home#index'

  devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations" } #, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    post 'pay', to: 'users/registrations#pay'
  end

  resources :charges

  get 'cart' => 'home#cart'
  get 'contact' => 'home#contact'
  get 'about' => 'home#about'
  get 'blog' => 'home#blog'
  get 'blog/post' => 'home#blog_post'
  get 'invoice' => 'home#invoice'
  get 'premium' => 'home#premium'

  get 'account' => 'account#index', as: :user
  patch 'account/update' => 'account#update'

end

skeleton/app/models/company.rb
class Company < ActiveRecord::Base
end

skeleton/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :website, :location, :markets, :high_concept_pitch, :why_us, :product)
    end
end

skeleton/app/helpers/companies_helper.rb
module CompaniesHelper
end

skeleton/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :markets %><br>
    <%= f.text_field :markets %>
  </div>
  <div class="field">
    <%= f.label :high_concept_pitch %><br>
    <%= f.text_field :high_concept_pitch %>
  </div>
  <div class="field">
    <%= f.label :why_us %><br>
    <%= f.text_area :why_us %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_area :product %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skeleton/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

skeleton/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Location</th>
      <th>Markets</th>
      <th>High concept pitch</th>
      <th>Why us</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.website %></td>
        <td><%= company.location %></td>
        <td><%= company.markets %></td>
        <td><%= company.high_concept_pitch %></td>
        <td><%= company.why_us %></td>
        <td><%= company.product %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

skeleton/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

skeleton/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<p>
  <strong>Location:</strong>
  <%= @company.location %>
</p>

<p>
  <strong>Markets:</strong>
  <%= @company.markets %>
</p>

<p>
  <strong>High concept pitch:</strong>
  <%= @company.high_concept_pitch %>
</p>

<p>
  <strong>Why us:</strong>
  <%= @company.why_us %>
</p>

<p>
  <strong>Product:</strong>
  <%= @company.product %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>