skeleton/config/routes.rb
Rails.application.routes.draw do

  resources :skills
  resources :skill_categories
  resources :projects

  resources :jobs
  get 'find/my/job' => 'jobs#find'

  resources :companies

  root 'home#index'

  devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations" } #, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    post 'pay', to: 'users/registrations#pay'
  end

  resources :charges

  get 'cart' => 'home#cart'
  get 'contact' => 'home#contact'
  get 'about' => 'home#about'
  get 'blog' => 'home#blog'
  get 'blog/post' => 'home#blog_post'
  get 'invoice' => 'home#invoice'
  get 'premium' => 'home#premium'

  get 'account' => 'account#index', as: :user
  patch 'account/update' => 'account#update'

end

skeleton/app/models/skill_category.rb
class SkillCategory < ActiveRecord::Base
end

skeleton/app/controllers/skill_categories_controller.rb
class SkillCategoriesController < ApplicationController
  before_action :set_skill_category, only: [:show, :edit, :update, :destroy]

  # GET /skill_categories
  # GET /skill_categories.json
  def index
    @skill_categories = SkillCategory.all
  end

  # GET /skill_categories/1
  # GET /skill_categories/1.json
  def show
  end

  # GET /skill_categories/new
  def new
    @skill_category = SkillCategory.new
  end

  # GET /skill_categories/1/edit
  def edit
  end

  # POST /skill_categories
  # POST /skill_categories.json
  def create
    @skill_category = SkillCategory.new(skill_category_params)

    respond_to do |format|
      if @skill_category.save
        format.html { redirect_to @skill_category, notice: 'Skill category was successfully created.' }
        format.json { render :show, status: :created, location: @skill_category }
      else
        format.html { render :new }
        format.json { render json: @skill_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skill_categories/1
  # PATCH/PUT /skill_categories/1.json
  def update
    respond_to do |format|
      if @skill_category.update(skill_category_params)
        format.html { redirect_to @skill_category, notice: 'Skill category was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill_category }
      else
        format.html { render :edit }
        format.json { render json: @skill_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_categories/1
  # DELETE /skill_categories/1.json
  def destroy
    @skill_category.destroy
    respond_to do |format|
      format.html { redirect_to skill_categories_url, notice: 'Skill category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill_category
      @skill_category = SkillCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_category_params
      params.require(:skill_category).permit(:name)
    end
end

skeleton/app/helpers/skill_categories_helper.rb
module SkillCategoriesHelper
end

skeleton/app/views/skill_categories/_form.html.erb
<%= form_for(@skill_category) do |f| %>
  <% if @skill_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill_category.errors.count, "error") %> prohibited this skill_category from being saved:</h2>

      <ul>
      <% @skill_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skeleton/app/views/skill_categories/edit.html.erb
<h1>Editing Skill Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill_category %> |
<%= link_to 'Back', skill_categories_path %>

skeleton/app/views/skill_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skill Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skill_categories.each do |skill_category| %>
      <tr>
        <td><%= skill_category.name %></td>
        <td><%= link_to 'Show', skill_category %></td>
        <td><%= link_to 'Edit', edit_skill_category_path(skill_category) %></td>
        <td><%= link_to 'Destroy', skill_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill category', new_skill_category_path %>

skeleton/app/views/skill_categories/new.html.erb
<h1>New Skill Category</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_categories_path %>

skeleton/app/views/skill_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill_category.name %>
</p>

<%= link_to 'Edit', edit_skill_category_path(@skill_category) %> |
<%= link_to 'Back', skill_categories_path %>